### ISSUE TITLE
Error pymailer.send_test()

### ISSUE THREAD

**Issue by lohriialo** [qoda/python-mailer#6]
Trying this out on localhost and running into errors, thought the error is my firewall so I changed network and tried but always throws 
> ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

Here's the trace:
```
Traceback (most recent call last):
  File "C:/Users/users/PycharmProjects/python-mailer/app.py", line 5, in <module>
    pymailer.send_test()
  File "C:\Users\users\PycharmProjects\python-mailer\pymailer.py", line 221, in send_test
    self.send(recipient_list=config.TEST_RECIPIENTS)
  File "C:\Users\users\PycharmProjects\python-mailer\pymailer.py", line 203, in send
    smtp_server = smtplib.SMTP(host=config.SMTP_HOST, port=config.SMTP_PORT)
  File "c:\python36\Lib\smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "c:\python36\Lib\smtplib.py", line 335, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "c:\python36\Lib\smtplib.py", line 306, in _get_socket
    self.source_address)
  File "c:\python36\Lib\socket.py", line 722, in create_connection
    raise err
  File "c:\python36\Lib\socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

**Comment by qoda** [comment]
Environment issue, not related to library.
